# -*- coding: utf-8 -*-
"""netflix_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yQmE6_Td5K2e-ymEyGpQnLHFQNrW40el
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("netflix_titles.csv")

df = pd.read_csv("netflix_titles.csv")

df.head()

df.tail()

df.shape

df.columns

df.info()

df.isnull().sum()

sns.heatmap(df.isnull())
plt.show

df['director'].fillna('Unknown')
df['country'].fillna('Unknown')
df['cast'].fillna('Unknown')
df['rating'].fillna(df['rating'].mode()[0])

df.duplicated().sum()

df.drop_duplicates(inplace=True)

sns.heatmap(df.isnull())
plt.show

df.dropna(inplace=True)

sns.heatmap(df.isnull())
plt.show()

df.isnull().sum()

df['type'].value_counts()

sns.countplot(x='type',data=df)
plt.title("MOVIES vs TV SHOWS on Netflix")
plt.show()

df['country'].value_counts().head(10)

plt.figure(figsize=(15,10))
df['country'].value_counts().head(10).plot(kind='bar')
plt.title("Top 10 countries on Netflix")
plt.xlabel("Country")
plt.ylabel("Number of Titles")
plt.xticks(rotation=45)
plt.show

df['rating'].value_counts()

plt.figure(figsize=(10,5))
sns.countplot(y='rating', data=df, order=df['rating'].value_counts().index)
plt.title("Netflix Content Ratings")
plt.show()

df['release_year'].value_counts().head(10)

plt.figure(figsize=(12,5))

df['release_year'].value_counts().sort_index().plot()

plt.title("Netflix Content Released by Year")
plt.xlabel("Year")
plt.ylabel("Number of Titles")

plt.show()

df['listed_in'].value_counts().head(10)

plt.figure(figsize=(10,5))

df['listed_in'].value_counts().head(10).plot(kind='barh')

plt.title("Top 10 Netflix Genres")
plt.xlabel("Number of Titles")
plt.ylabel("Genre")

plt.show()

df['director'].value_counts().head(10)

plt.figure(figsize=(12,5))

df['director'].value_counts().head(10).plot(kind='barh')

plt.title("Top 10 Directors on Netflix")
plt.xlabel("Director")
plt.ylabel("Number of Titles")

plt.xticks(rotation=45)
plt.show()

df['date_added'] = pd.to_datetime(df['date_added'], errors='coerce')

df['year_added'] = df['date_added'].dt.year

df[['title','year_added']].head()

plt.figure(figsize=(12,5))

df['year_added'].value_counts().sort_index().plot()

plt.title("Content Added to Netflix by Year")
plt.xlabel("Year")
plt.ylabel("Number of Titles Added")

plt.show()

df['year_added'].value_counts().idxmax()

df['year_added'].value_counts().max()

movies = df[df['type'] == 'Movie'].copy()

movies['duration'].head()

movies['duration_num'] = movies.loc[:,'duration'].str.replace(' min','').astype(int)

movies.sort_values('duration_num', ascending=False)[['title','duration_num']].head(10)

!jupyter nbconvert --to html netflix_analysis.ipynb